name: Code Quality
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Check PHP code quality
        run: vendor/bin/phpcs --standard=PSR12 src
